services:
  monitor:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: linux-server-monitor

    environment:
      CPU_WARNING: "70"
      CPU_CRITICAL: "90"
      MEMORY_WARNING: "70"
      MEMORY_CRITICAL: "90"
      DISK_WARNING: "70"
      DISK_CRITICAL: "90"

    volumes:
      - ./logs:/app/logs
      - ./state:/app/state
