name: Linux Server Monitor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: |
          chmod +x monitor.sh
          chmod +x tests/test.sh

      - name: Run tests
        run: ./tests/test.sh

      - name: Build Docker image
        run: docker build -t linux-server-monitor:test .

      - name: Test Docker container
        run: |
          docker run --rm linux-server-monitor:test > output.txt
          cat output.txt
          grep "Overall Status" output.txt
