name: Linux Server Monitor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Bash syntax
        run: bash -n monitor.sh

      - name: Make script executable
        run: chmod +x monitor.sh

      - name: Build Docker image
        run: docker build -t linux-server-monitor:test .

      - name: Test Docker container
        run: docker run --rm linux-server-monitor:test
